import { Image } from '@tarojs/components';
import Taro from '@tarojs/taro';

const iconPackages = require('./lucide-packages.cjs') as Record<string, string[]>;
const iconAssetPath = (name: string, variant: string) => {
  const route = Taro.getCurrentPages().at(-1)?.route ?? '';
  const currentPackage = route.split('/')[0];
  const packagePath = iconPackages[name]?.includes(currentPackage) ? `/${currentPackage}/assets/lucide` : '/assets/lucide';
  return `${packagePath}/${name}-${variant}.svg`;
};

type IconProps = { size?: number; color?: string; className?: string };
const icon = (name: string) => function TaroImageIcon({ size = 24, color = 'currentColor', className = '' }: IconProps) {
  const variant = color === '#FFFFFF' || className.includes('text-white') ? 'light' : 'ink';
  return <Image
    src={iconAssetPath(name, variant)}
    mode="aspectFit"
    className={className}
    style={{ width: size, height: size, flexShrink: 0 }}
  />;
};

export const ArrowLeftRight = icon('arrowleftright');
export const ArrowRightLeft = icon('arrowrightleft');
export const ArrowUpRight = icon('arrowupright');
export const ArrowLeft = icon('arrowleft');
export const AlarmClock = icon('alarmclock');
export const AlertTriangle = icon('alerttriangle');
export const AlertCircle = icon('alertcircle');
export const AppWindow = icon('appwindow');
export const Apple = icon('apple');
export const Bell = icon('bell');
export const BellRing = icon('bellring');
export const BookOpenText = icon('bookopentext');
export const BookOpenCheck = icon('bookopencheck');
export const Brain = icon('brain');
export const Camera = icon('camera');
export const CalendarDays = icon('calendardays');
export const CalendarCheck = icon('calendarcheck');
export const CircleHelp = icon('circlehelp');
export const Check = icon('check');
export const CheckCircle2 = icon('checkcircle2');
export const Citrus = icon('citrus');
export const ChevronRight = icon('chevronright');
export const ChevronLeft = icon('chevronleft');
export const ChevronDown = icon('chevrondown');
export const Clock3 = icon('clock3');
export const Crown = icon('crown');
export const Cloud = icon('cloud');
export const Database = icon('database');
export const Download = icon('download');
export const Edit2 = icon('edit2');
export const Eye = icon('eye');
export const ExternalLink = icon('externallink');
export const Flame = icon('flame');
export const FolderPlus = icon('folderplus');
export const GitCompareArrows = icon('gitcomparearrows');
export const Heart = icon('heart');
export const Handshake = icon('handshake');
export const HelpCircle = icon('helpcircle');
export const History = icon('history');
export const ImageDown = icon('imagedown');
export const Info = icon('info');
export const KeyRound = icon('keyround');
export const Languages = icon('languages');
export const Layers3 = icon('layers3');
export const Layers = icon('layers');
export const LetterText = icon('lettertext');
export const ListChecks = icon('listchecks');
export const ListOrdered = icon('listordered');
export const LoaderCircle = icon('loadercircle');
export const Loader2 = icon('loader2');
export const Lock = icon('lock');
export const LockKeyhole = icon('lockkeyhole');
export const LogOut = icon('logout');
export const MessageCircle = icon('messagecircle');
export const Merge = icon('merge');
export const Mic = icon('mic');
export const Minus = icon('minus');
export const Moon = icon('moon');
export const Mountain = icon('mountain');
export const Music = icon('music');
export const PackageCheck = icon('packagecheck');
export const Palette = icon('palette');
export const NotebookPen = icon('notebookpen');
export const Pause = icon('pause');
export const PenLine = icon('penline');
export const PencilLine = icon('pencilline');
export const Pencil = icon('pencil');
export const Play = icon('play');
export const Plus = icon('plus');
export const Puzzle = icon('puzzle');
export const ReceiptText = icon('receipttext');
export const Repeat2 = icon('repeat2');
export const Repeat = icon('repeat');
export const RotateCcw = icon('rotateccw');
export const RefreshCw = icon('refreshcw');
export const ScrollText = icon('scrolltext');
export const Search = icon('search');
export const Send = icon('send');
export const Settings = icon('settings');
export const Share2 = icon('share2');
export const Shield = icon('shield');
export const ShieldCheck = icon('shieldcheck');
export const Shirt = icon('shirt');
export const SkipForward = icon('skipforward');
export const SlidersHorizontal = icon('slidershorizontal');
export const Shuffle = icon('shuffle');
export const Smartphone = icon('smartphone');
export const Sparkles = icon('sparkles');
export const Sprout = icon('sprout');
export const Star = icon('star');
export const Sun = icon('sun');
export const StickyNote = icon('stickynote');
export const Target = icon('target');
export const Timer = icon('timer');
export const Ticket = icon('ticket');
export const Trash2 = icon('trash2');
export const Trophy = icon('trophy');
export const Type = icon('type');
export const Undo2 = icon('undo2');
export const Upload = icon('upload');
export const User = icon('user');
export const UserRound = icon('userround');
export const Volume2 = icon('volume2');
export const X = icon('x');
export const XCircle = icon('xcircle');
