GRAMMAR_POINTS = [
    {
        "pattern": "〜ています",
        "meaning": "正在……；状态持续",
        "prompt": "表示动作正在进行，或动作结果留下的状态。",
        "formation": "动词て形 + います",
        "example_jp": "今、日本語を勉強しています。",
        "example_meaning": "我现在正在学日语。",
        "notes": "瞬间动词常表示结果状态，比如 結婚しています 表示已婚。",
        "confusions": "〜ます；〜ました",
        "level": "N5",
        "importance": 5,
    },
    {
        "pattern": "〜てもいいです",
        "meaning": "可以……",
        "prompt": "表示许可：可以做某事。",
        "formation": "动词て形 + もいいです",
        "example_jp": "ここで写真を撮ってもいいです。",
        "example_meaning": "可以在这里拍照。",
        "notes": "疑问句常用于请求许可。",
        "confusions": "〜てはいけません",
        "level": "N5",
        "importance": 5,
    },
    {
        "pattern": "〜てはいけません",
        "meaning": "不可以……",
        "prompt": "表示禁止：不能做某事。",
        "formation": "动词て形 + はいけません",
        "example_jp": "ここでタバコを吸ってはいけません。",
        "example_meaning": "不能在这里抽烟。",
        "notes": "语气比较正式；口语可说 だめです。",
        "confusions": "〜てもいいです；〜ないでください",
        "level": "N5",
        "importance": 5,
    },
    {
        "pattern": "〜てください",
        "meaning": "请……",
        "prompt": "请对方做某事。",
        "formation": "动词て形 + ください",
        "example_jp": "もう一度言ってください。",
        "example_meaning": "请再说一遍。",
        "notes": "比命令柔和，但仍然是请求对方行动。",
        "confusions": "〜ないでください",
        "level": "N5",
        "importance": 5,
    },
    {
        "pattern": "〜ないでください",
        "meaning": "请不要……",
        "prompt": "请对方不要做某事。",
        "formation": "动词ない形去掉い? 不去掉：动词ない形 + でください",
        "example_jp": "ここに車を止めないでください。",
        "example_meaning": "请不要把车停在这里。",
        "notes": "ない 后面直接接 でください。",
        "confusions": "〜てください；〜てはいけません",
        "level": "N5",
        "importance": 5,
    },
    {
        "pattern": "〜たいです",
        "meaning": "想……",
        "prompt": "表达自己的愿望：想做某事。",
        "formation": "动词ます形去掉ます + たいです",
        "example_jp": "日本へ行きたいです。",
        "example_meaning": "我想去日本。",
        "notes": "通常说自己的愿望；第三人称愿望常用 〜たがっています。",
        "confusions": "〜ほしいです",
        "level": "N5",
        "importance": 5,
    },
    {
        "pattern": "〜たことがあります",
        "meaning": "曾经……过",
        "prompt": "表示过去经历：曾经做过某事。",
        "formation": "动词た形 + ことがあります",
        "example_jp": "富士山に登ったことがあります。",
        "example_meaning": "我爬过富士山。",
        "notes": "重点是有没有这种经历，不是具体什么时候。",
        "confusions": "〜ました",
        "level": "N5",
        "importance": 5,
    },
    {
        "pattern": "〜たり〜たりします",
        "meaning": "又……又……；列举动作",
        "prompt": "从多个动作里举例说明。",
        "formation": "动词た形 + り、动词た形 + りします",
        "example_jp": "休みの日は映画を見たり、散歩したりします。",
        "example_meaning": "休息日会看看电影、散散步之类。",
        "notes": "不是完整列举，只是举几个代表例。",
        "confusions": "〜て、〜て",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜から",
        "meaning": "因为……",
        "prompt": "说明原因、理由。",
        "formation": "普通形/礼貌形 + から",
        "example_jp": "雨が降っていますから、出かけません。",
        "example_meaning": "因为在下雨，所以不出门。",
        "notes": "语气直接，常用于主观说明。",
        "confusions": "〜ので",
        "level": "N5",
        "importance": 5,
    },
    {
        "pattern": "〜ので",
        "meaning": "因为……",
        "prompt": "较客观、较柔和地说明原因。",
        "formation": "普通形 + ので；な形容词/名词 + なので",
        "example_jp": "明日は試験なので、早く寝ます。",
        "example_meaning": "因为明天考试，所以早点睡。",
        "notes": "比 から 更柔和，常用于解释情况。",
        "confusions": "〜から",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜でしょう",
        "meaning": "大概……吧",
        "prompt": "表示推测。",
        "formation": "普通形 + でしょう",
        "example_jp": "明日は寒いでしょう。",
        "example_meaning": "明天大概会冷吧。",
        "notes": "礼貌说法；口语普通体常用 だろう。",
        "confusions": "〜かもしれません",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜かもしれません",
        "meaning": "也许……",
        "prompt": "表示可能性不高或不确定的推测。",
        "formation": "普通形 + かもしれません",
        "example_jp": "午後から雨が降るかもしれません。",
        "example_meaning": "下午也许会下雨。",
        "notes": "比 でしょう 更不确定。",
        "confusions": "〜でしょう",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜なければなりません",
        "meaning": "必须……",
        "prompt": "表示义务：必须做某事。",
        "formation": "动词ない形去い + ければなりません",
        "example_jp": "毎日勉強しなければなりません。",
        "example_meaning": "每天必须学习。",
        "notes": "口语常缩成 なきゃ。",
        "confusions": "〜なくてもいいです",
        "level": "N5",
        "importance": 5,
    },
    {
        "pattern": "〜なくてもいいです",
        "meaning": "不……也可以",
        "prompt": "表示没有必要做某事。",
        "formation": "动词ない形去い + くてもいいです",
        "example_jp": "明日は来なくてもいいです。",
        "example_meaning": "明天不来也可以。",
        "notes": "不是禁止，而是不用做。",
        "confusions": "〜なければなりません",
        "level": "N5",
        "importance": 5,
    },
    {
        "pattern": "〜ましょう",
        "meaning": "一起……吧",
        "prompt": "提议一起做某事。",
        "formation": "动词ます形去ます + ましょう",
        "example_jp": "一緒に帰りましょう。",
        "example_meaning": "一起回去吧。",
        "notes": "也可表示主动提出帮助。",
        "confusions": "〜ませんか",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜ませんか",
        "meaning": "要不要……",
        "prompt": "委婉邀请对方做某事。",
        "formation": "动词ます形否定疑问",
        "example_jp": "一緒に映画を見ませんか。",
        "example_meaning": "要不要一起看电影？",
        "notes": "比 ましょう 更像询问对方意愿。",
        "confusions": "〜ましょう",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜より〜のほうが",
        "meaning": "比起……更……",
        "prompt": "比较两者，指出后者更怎样。",
        "formation": "AよりBのほうが + 形容词",
        "example_jp": "バスより電車のほうが速いです。",
        "example_meaning": "比起公交，电车更快。",
        "notes": "更强的一方放在 のほうが 前。",
        "confusions": "〜ほど〜ない",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜ほど〜ない",
        "meaning": "没有……那么……",
        "prompt": "比较两者，表示不如对方。",
        "formation": "AはBほど + 否定",
        "example_jp": "今日は昨日ほど寒くないです。",
        "example_meaning": "今天没有昨天那么冷。",
        "notes": "后面一定是否定。",
        "confusions": "〜より〜のほうが",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜のが上手です",
        "meaning": "擅长……",
        "prompt": "表示擅长做某事。",
        "formation": "动词辞书形 + のが上手です",
        "example_jp": "彼は料理を作るのが上手です。",
        "example_meaning": "他擅长做饭。",
        "notes": "把动作名词化后评价。",
        "confusions": "〜のが好きです",
        "level": "N5",
        "importance": 3,
    },
    {
        "pattern": "〜のが好きです",
        "meaning": "喜欢……",
        "prompt": "表示喜欢做某事。",
        "formation": "动词辞书形 + のが好きです",
        "example_jp": "音楽を聞くのが好きです。",
        "example_meaning": "我喜欢听音乐。",
        "notes": "の 把前面的动作变成名词。",
        "confusions": "〜たいです",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜前に",
        "meaning": "在……之前",
        "prompt": "表示做某事之前。",
        "formation": "动词辞书形 + 前に；名词 + の前に",
        "example_jp": "寝る前に歯を磨きます。",
        "example_meaning": "睡觉前刷牙。",
        "notes": "前面的动词用辞书形，不随时态变化。",
        "confusions": "〜後で",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜後で",
        "meaning": "在……之后",
        "prompt": "表示做某事之后。",
        "formation": "动词た形 + 後で；名词 + の後で",
        "example_jp": "ご飯を食べた後で、散歩します。",
        "example_meaning": "吃完饭后散步。",
        "notes": "动词要用た形。",
        "confusions": "〜前に；〜てから",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜てから",
        "meaning": "……之后再……",
        "prompt": "强调先后顺序：做完前项再做后项。",
        "formation": "动词て形 + から",
        "example_jp": "宿題をしてから、ゲームをします。",
        "example_meaning": "做完作业后再玩游戏。",
        "notes": "比 後で 更强调顺序。",
        "confusions": "〜後で",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜ながら",
        "meaning": "一边……一边……",
        "prompt": "两个动作同时进行。",
        "formation": "动词ます形去ます + ながら",
        "example_jp": "音楽を聞きながら勉強します。",
        "example_meaning": "一边听音乐一边学习。",
        "notes": "主动作通常在句末。",
        "confusions": "〜ている間に",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜と思います",
        "meaning": "我想/认为……",
        "prompt": "表达想法、判断。",
        "formation": "普通形 + と思います",
        "example_jp": "明日は雨が降ると思います。",
        "example_meaning": "我觉得明天会下雨。",
        "notes": "引用自己的想法。",
        "confusions": "〜と言います",
        "level": "N5",
        "importance": 5,
    },
    {
        "pattern": "〜と言います",
        "meaning": "说……；叫作……",
        "prompt": "引用说话内容，或说明名称。",
        "formation": "普通形/内容 + と言います",
        "example_jp": "先生は明日試験があると言いました。",
        "example_meaning": "老师说明天有考试。",
        "notes": "引用内容用 と。",
        "confusions": "〜と思います",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜んです",
        "meaning": "解释说明",
        "prompt": "补充背景、解释原因、带有说明语气。",
        "formation": "普通形 + んです；名词/な形容词 + なんです",
        "example_jp": "頭が痛いんです。",
        "example_meaning": "我是头疼。",
        "notes": "常用于解释情况或引出请求。",
        "confusions": "普通陈述句",
        "level": "N5",
        "importance": 4,
    },
    {
        "pattern": "〜すぎます",
        "meaning": "太……；过度……",
        "prompt": "表示程度过头。",
        "formation": "动词ます形去ます/い形去い/な形词干 + すぎます",
        "example_jp": "昨日は食べすぎました。",
        "example_meaning": "昨天吃太多了。",
        "notes": "可用于动词和形容词。",
        "confusions": "とても",
        "level": "N4",
        "importance": 4,
    },
    {
        "pattern": "〜やすいです",
        "meaning": "容易……",
        "prompt": "表示某动作容易发生或容易做。",
        "formation": "动词ます形去ます + やすいです",
        "example_jp": "このペンは書きやすいです。",
        "example_meaning": "这支笔很好写。",
        "notes": "形容动作的难易。",
        "confusions": "〜にくいです",
        "level": "N4",
        "importance": 4,
    },
    {
        "pattern": "〜にくいです",
        "meaning": "难以……",
        "prompt": "表示某动作难做或不容易发生。",
        "formation": "动词ます形去ます + にくいです",
        "example_jp": "この説明は分かりにくいです。",
        "example_meaning": "这个说明很难懂。",
        "notes": "和 やすい 相反。",
        "confusions": "〜やすいです",
        "level": "N4",
        "importance": 4,
    },
    {
        "pattern": "〜ほうがいいです",
        "meaning": "最好……",
        "prompt": "给建议：最好做或不做某事。",
        "formation": "动词た形/ない形 + ほうがいいです",
        "example_jp": "早く寝たほうがいいです。",
        "example_meaning": "最好早点睡。",
        "notes": "肯定建议常用た形，否定建议用ない形。",
        "confusions": "〜なければなりません",
        "level": "N4",
        "importance": 5,
    },
]
