const app = document.querySelector('#app');
let page = 'home', question = 0, score = 0, answered = false;
const questions = [
  {word:'かける', reading:'掛ける', prompt:'「眼鏡を かける」中最贴近的意思是？', options:['花费（时间）','戴上','拨打（电话）','启动'], correct:1, explain:'这里的 かける 表示「把某物置于身体上」，用于眼镜、耳机等。它和「時間をかける（花费时间）」是不同义项。', ex:'眼鏡をかけて、本を読みます。'},
  {word:'と', reading:'助词', prompt:'「友達と映画を見た」中的 と 表示？', options:['引用','条件','共同动作对象','结果'], correct:2, explain:'と 在这里连接共同完成动作的人，意思是「和」。它与「雨が降ると…」中的条件用法不同。', ex:'友達と一緒に勉強します。'}
];
function nav(active=page){return `<aside class="side"><div><p class="side-label">LEARNING MAP</p><nav class="nav"><button class="${active==='home'?'active':''}" data-page="home"><span class="num">01</span>今日</button><button data-page="vocab"><span class="num">02</span>单词馆</button><button data-page="grammar"><span class="num">03</span>狐狸语法</button><button data-page="compare"><span class="num">04</span>辨析室</button><button data-page="read"><span class="num">05</span>猫头鹰阅读</button><button data-page="insights"><span class="num">06</span>学习记录</button></nav></div><div class="streak"><span>安静地，持续地学习</span><b>18 日</b><span>这是你的本周第 4 次来访</span></div></aside>`}
function frame(content, active){app.innerHTML=`<div class="shell"><header class="topbar"><button class="wordmark" data-page="home">Master Nihongo <small>学びの動物園</small></button><div class="top-actions"><button class="quiet">⌘ K　搜索</button><span class="avatar">林</span></div></header><div class="layout">${nav(active)}<main>${content}</main></div></div><div class="toast" id="toast"></div>`; bindNav()}
function home(){page='home';frame(`<p class="eyebrow">THURSDAY · JUL 23</p><h1 class="headline">今天，也为日语留一点安静的时间。</h1><section class="today"><div><b>你的今日学习</b><p>从上次停下的地方继续。先处理记忆正好开始变淡的内容。</p><div class="facts"><span class="fact" id="review-count">42<small>待复习单词</small></span><span class="fact">20<small>新单词</small></span><span class="fact">2<small>语法单元</small></span><span class="fact">35′<small>预计时间</small></span></div></div><button class="start" id="start">开始今日学习　→</button></section><div class="dashboard-grid"><section><div class="section-title"><span>学习动物园</span><button id="map-link">打开学习地图 ↗</button></div><div class="map"><i class="grass a"></i><i class="grass b"></i><span class="gate">ENTRANCE / 学习入口</span><button class="habitat cat" data-page="vocab"><b>猫馆</b><span>VOCABULARY</span></button><button class="habitat fox" data-page="grammar"><b>狐狸馆</b><span>GRAMMAR</span></button><button class="habitat owl" data-page="read"><b>猫头鹰馆</b><span>READING</span></button><button class="habitat panda" data-page="compare"><b>熊猫馆</b><span>REVIEW</span></button><button class="habitat capy" data-page="compare"><b>水豚区</b><span>COMPARE</span></button><i class="path one"></i><i class="path two"></i></div></section><section><div class="section-title"><span>最近进度</span></div><div class="progress-list"><div class="progress-item"><div class="row"><span>N4 词汇</span><b>67%</b></div><div class="bar"><i style="width:67%"></i></div></div><div class="progress-item"><div class="row"><span>基础语法</span><b>42%</b></div><div class="bar"><i style="width:42%"></i></div></div><div class="progress-item"><div class="row"><span>阅读耐力</span><b>31%</b></div><div class="bar"><i style="width:31%"></i></div></div></div><div class="recommend"><span class="eyebrow">TODAY'S NOTE</span><p>你最近容易混淆「ようだ」「らしい」「そうだ」。</p><button class="link" data-page="compare">做一次辨析练习 →</button></div><div class="week"><i class="day done"></i><i class="day done"></i><i class="day done"></i><i class="day done"></i><i class="day done"></i><i class="day today"></i><i class="day"></i></div></section></div>`, 'home');document.querySelector('#start').onclick=review;}
function review(){page='vocab';question=0;score=0;answered=false;renderQuestion()}
function renderQuestion(){const q=questions[question];frame(`<section class="study"><div class="study-head"><button data-page="home">← 退出今日学习</button><span>复习 ${question+1} / ${questions.length+4}</span><span>⌘ 1–4 选择</span></div><div class="meter"><i style="width:${((question+1)/(questions.length+4))*100}%"></i></div><div class="question-type">MULTIPLE MEANING · 义项辨析</div><div class="word">${q.word}</div><div class="reading">${q.reading}</div><p class="prompt">${q.prompt}</p><div class="answers">${q.options.map((x,i)=>`<button class="answer" data-answer="${i}"><span class="key">${i+1}</span><strong>${x}</strong></button>`).join('')}</div><div class="feedback" id="feedback"></div><div class="rating" id="rating"><button>完全不会</button><button>模糊记得</button><button>记得</button><button id="mastered">非常熟悉</button></div><p class="shortcut">选择答案后，按 Enter 进入下一题</p></section>`, 'vocab'); document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));}
function answer(index){if(answered)return;answered=true;const q=questions[question], correct=index===q.correct;if(correct)score++;document.querySelectorAll('[data-answer]').forEach((b,i)=>b.classList.add(i===q.correct?'correct':i===index?'wrong':''));const f=document.querySelector('#feedback');f.className='feedback show '+(correct?'':'error');f.innerHTML=`<h3>${correct?'答对了，记忆会更稳一点。':'这一题值得停下来看看。'}</h3><p>${q.explain}</p><p class="example">${q.ex}</p><div class="feedback-actions"><span class="eyebrow">${correct?'下次复习：4 天后':'下次复习：明天'}</span><button class="next" id="next">下一题　↵</button></div>`;document.querySelector('#rating').classList.add('show');document.querySelector('#next').onclick=next;document.querySelector('#mastered').onclick=()=>toast('已记录为「非常熟悉」');}
function next(){if(question<questions.length-1){question++;answered=false;renderQuestion()}else complete()}
function complete(){page='vocab';frame(`<section class="complete"><div class="complete-mark">よくできました</div><h1>今天的复习，完成了。</h1><p>不必追赶进度。稳定地回来，已经足够。</p><div class="summary"><div><b>${score}/${questions.length}</b><span>本次正确</span></div><div><b>+8</b><span>掌握词汇</span></div><div><b>18 日</b><span>连续学习</span></div></div><button class="start" id="back-home">回到今日　→</button></section>`,'vocab');document.querySelector('#back-home').onclick=()=>{home();toast('今日复习已更新：42 → 34')};}
function placeholder(name,detail){page=name;frame(`<section class="placeholder"><p class="eyebrow">MASTER NIHONGO / ${name.toUpperCase()}</p><h1>${detail.title}</h1><p style="color:var(--muted);max-width:540px;line-height:1.8">${detail.text}</p><div class="feature-columns">${detail.items.map(([a,b])=>`<article class="feature"><b>${a}</b><p>${b}</p></article>`).join('')}</div></section>`,name)}
const destinations={grammar:{title:'狐狸馆：语法的结构感',text:'用接续、场景和相似表达之间的距离来理解语法，而不是孤立背诵。',items:[['〜なければならない','动词ない形 → 去「い」→ ければならない'],['核心场景','义务、规定与不得不做的事'],['相似表达','〜なくてはいけない · 〜べきだ']]},compare:{title:'辨析室：让相似的表达各就其位',text:'把容易混淆的形式并排放在真实句子里，看见它们的语气、信息来源和使用边界。',items:[['ようだ','基于观察与推测'],['らしい','听闻、典型特征'],['そうだ','样态 / 传闻，两种入口']]},read:{title:'猫头鹰馆：留给文章一点空间',text:'阅读不是测试速度。可以点击词语、显示假名、标记表达，然后回看文章的骨架。',items:[['読書時間','字体与阅读节奏可调'],['語彙メモ','点击词语，放入个人词表'],['文章分析','题目完成后，再拆解结构']]},insights:{title:'学习记录：看见缓慢积累',text:'真正重要的不是学了多久，而是哪些词开始稳住、哪些语法仍需要再见一次。',items:[['掌握词汇','1,284 · N4 为当前重心'],['易混淆','ようだ / らしい / そうだ'],['复习完成度','近 30 天，78%']]}};
function bindNav(){document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>{const p=el.dataset.page;if(p==='home')home();else if(p==='vocab')review();else placeholder(p,destinations[p])}));}
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
document.addEventListener('keydown',e=>{if(page==='vocab'&&!answered&&['1','2','3','4'].includes(e.key))answer(+e.key-1);if(page==='vocab'&&answered&&e.key==='Enter')next()});home();
